# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
  imageName: 'janusgraph-server'
  dockerId: 'bernard'
  pswd: 'Rl7lUX8K79cISRw/jknXgURvXR7UOGbK'
  tagName: 'latest'

resources:
  containers:
  - container: janusgraph
    image: $(imageName)
    ports:
    - 7000:7000 7001:7001 7199:7199 8182:8182 9042:9042 9160:9160 9200:9200    

jobs:

- job: CreateImage
  displayName: Create required image
  continueOnError: false

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: | 
       docker build -t $(dockerId).azurecr.io/$(imageName) https://github.com/bwatson-rti-org/janusgraph.git#:janusgraph-dist/janusgraph-dist-hadoop-2
       docker login -u $(dockerId) -p $(pswd) $(dockerId).azurecr.io
       #docker tag  $(imageName) $(dockerId).azurecr.io/$(imageName):$(Build.BuildId)
       docker push $(dockerId).azurecr.io/$(imageName)
    continueOnError: false    

- job: BuildImage
  displayName: Build
  dependsOn: CreateImage
  continueOnError: false

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: docker exec -i -t janusgraph /var/janusgraph/bin/janusgraph.sh
    displayName: 'Execute script'
    continueOnError: false