
# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
  group: Janusgraph  
  imageName: 'janusgraph-server'
  dockerId: 'Bernard'
  username: bwatson@rti.org  
  tagName: 'latest'

resources:
  containers:
  - container: janusgraph
    image: $(imageName)
    ports:
    - 7000:7000 7001:7001 7199:7199 8182:8182 9042:9042 9160:9160 9200:9200    

jobs:

- job: CreateAndRegisterImage
  displayName: Create image and push it to registry
  continueOnError: false

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: | 
       docker build --build-arg server_unzip=unzip --build-arg file_part=janusgraph-0.3.2-SNAPSHOT-hadoop2 --build-arg rti_secret=$(rti_secret) -t $(dockerId).azurecr.io/$(imageName) https://github.com/bwatson-rti-org/janusgraph.git#:janusgraph-dist/janusgraph-dist-hadoop-2
       docker login -u $(dockerId) -p $(reg_secret) $(dockerId).azurecr.io           
       docker push $(dockerId).azurecr.io/$(imageName)        

- job: DeployAndStartContainer
  displayName: Deploy and start container
  dependsOn: CreateAndRegisterImage
  continueOnError: false

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: |
        Write Host "Value of rti_secret is $(rti_secret)"
        az login -u $(username) -p $(JanusgraphSecret)       
        az container create -g MSA-Catapult-East-Dev -n janusgraph-server --image bernard.azurecr.io/janusgraph-server:latest --command-line "tail -f /dev/null" --location eastus --dns-name-label janusgraph --registry-login-server bernard.azurecr.io --os-type Linux --cpu 1 --restart-policy Never --ip-address public --ports 80 8182 --protocol TCP --memory 2 --registry-username Bernard --registry-password $(reg_secret)
        az container exec -g MSA-Catapult-East-Dev --name janusgraph-server --container-name janusgraph-server --exec-command "/bin/bash"
        var/janusgraph/bin/janusgraph.sh -v start
    