# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

variables:
  imageName: 'janusgraph-server:latest'

resources:
  containers:
  - container: janusgraph
    image: $(imageName)
    ports:
    - 7000:7000 7001:7001 7199:7199 8182:8182 9042:9042 9160:9160 9200:9200    

jobs:

- job: CreateImage
  displayName: Create required image
  condition: and(succeeded(), eq(variables['Azure.CreateImage'], 'true'))

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: docker build -f Dockerfile -t $(imageName) .
    displayName: 'docker build'
    #continueOnError: false

- job: BuildImage
  displayName: Build
  dependsOn: CreateImage
  condition: and(succeeded(), eq(variables['Azure.CreateImage'], 'true'))

  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - script: docker exec -i -t janusgraph /var/janusgraph/bin/janusgraph.sh
    displayName: 'Execute script'
    continueOnError: false